# Generated by Django 4.2.23 on 2025-10-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planning_notes",
                    models.TextField(
                        blank=True, help_text="Pre-session planning notes", null=True
                    ),
                ),
                (
                    "session_notes",
                    models.TextField(
                        blank=True, help_text="During/post-session notes", null=True
                    ),
                ),
                ("session_date", models.DateField(help_text="Date of the session")),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Associated campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date", "campaign__title"],
            },
        ),
    ]
