# Generated by Django 4.2.23 on 2025-10-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_notes', models.TextField(blank=True, help_text='Pre-session planning notes, preparation, and DM notes', null=True)),
                ('session_notes', models.TextField(blank=True, help_text='Notes taken during or after the session, including what happened', null=True)),
                ('session_date', models.DateField(blank=True, help_text='The date when this session took place', null=True)),
                ('campaign', models.ForeignKey(help_text='The campaign this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-session_date', 'campaign__title'],
            },
        ),
    ]
