# Generated by Django 4.2.23 on 2025-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_date",
            field=models.DateField(
                blank=True, help_text="Date of the session", null=True
            ),
        ),
    ]
