# Generated by Django 4.2.23 on 2025-10-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_character_requirements_and_more'),
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='campaign',
            field=models.ForeignKey(help_text='The campaign this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='session',
            name='planning_notes',
            field=models.TextField(blank=True, help_text='Pre-session planning notes, preparation, and DM notes', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(blank=True, help_text='The date when this session took place', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_notes',
            field=models.TextField(blank=True, help_text='Notes taken during or after the session, including what happened', null=True),
        ),
    ]
