# Generated by Django 4.2.23 on 2025-08-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLAYER', 'Player'), ('NPC', 'NPC')], default='PLAYER', max_length=7)),
                ('name', models.CharField(max_length=120)),
                ('race', models.CharField(blank=True, max_length=80, null=True)),
                ('character_class', models.CharField(blank=True, max_length=80, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['type', 'name'],
            },
        ),
    ]
