# Generated by Django 4.2.23 on 2025-10-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorcode',
            name='code',
            field=models.CharField(help_text='6-digit numeric backup code', max_length=6),
        ),
        migrations.AlterField(
            model_name='twofactorcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the code was generated'),
        ),
        migrations.AlterField(
            model_name='twofactorcode',
            name='expires_at',
            field=models.DateTimeField(help_text='Timestamp when the code expires'),
        ),
        migrations.AlterField(
            model_name='twofactorcode',
            name='used',
            field=models.BooleanField(default=False, help_text='Whether this code has been used for authentication'),
        ),
        migrations.AlterField(
            model_name='twofactorcode',
            name='user',
            field=models.ForeignKey(help_text='The user this backup code belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user account was created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email address (used as username for login)", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number for contact purposes', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled for this user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='Base32-encoded secret key for TOTP generation', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the user account was last modified'),
        ),
    ]
