# Generated by Django 4.2.23 on 2025-09-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='The date this planning session is for')),
                ('title', models.CharField(help_text='Brief title for this planning session', max_length=200)),
                ('notes', models.TextField(help_text='Your preparation notes for this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_sessions', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Planning Session',
                'verbose_name_plural': 'Planning Sessions',
                'ordering': ['-session_date', '-created_at'],
                'unique_together': {('campaign', 'session_date')},
            },
        ),
    ]
