# Generated by Django 4.2.23 on 2025-09-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the encounter (e.g., 'Goblin Ambush')", max_length=120)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this encounter is currently active')),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_turn', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the participant', max_length=120)),
                ('initiative_roll', models.PositiveIntegerField(help_text='Total initiative value')),
                ('is_turn_complete', models.BooleanField(default=False, help_text='Whether this participant has completed their turn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='combat_tracker.combatencounter')),
            ],
            options={
                'ordering': ['-initiative_roll'],
            },
        ),
    ]
