# Generated by Django 4.2.23 on 2025-10-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monsters", "0004_monster_gear"),
        ("campaigns", "0002_auto_20251004_1510"),
        ("players", "0004_player_subclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Encounter name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Encounter description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Associated campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "monsters",
                    models.ManyToManyField(
                        help_text="Monsters in this encounter",
                        related_name="encounters",
                        to="monsters.monster",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        help_text="Players participating in this encounter",
                        related_name="encounters",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
