# Generated by Django 4.2.23 on 2025-09-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the encounter (e.g., 'Goblin Ambush')", max_length=120)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this encounter is currently active')),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_turn', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the participant', max_length=120)),
                ('initiative_roll', models.PositiveIntegerField(help_text='Total initiative value')),
                ('is_turn_complete', models.BooleanField(default=False, help_text='Whether this participant has completed their turn')),
                ('is_dead', models.BooleanField(default=False, help_text='Whether this participant is dead (0 or negative HP)')),
                ('armor_class', models.PositiveIntegerField(blank=True, help_text='Current Armor Class (can be modified by spells)', null=True)),
                ('hit_points', models.IntegerField(blank=True, help_text='Current Hit Points (can go negative)', null=True)),
                ('max_hit_points', models.PositiveIntegerField(blank=True, help_text='Maximum Hit Points', null=True)),
                ('speed', models.CharField(blank=True, help_text='Movement speed', max_length=50, null=True)),
                ('challenge_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Challenge Rating', max_digits=3, null=True)),
                ('strength', models.PositiveIntegerField(blank=True, null=True)),
                ('dexterity', models.PositiveIntegerField(blank=True, null=True)),
                ('constitution', models.PositiveIntegerField(blank=True, null=True)),
                ('intelligence', models.PositiveIntegerField(blank=True, null=True)),
                ('wisdom', models.PositiveIntegerField(blank=True, null=True)),
                ('charisma', models.PositiveIntegerField(blank=True, null=True)),
                ('strength_save', models.IntegerField(blank=True, help_text='Strength saving throw bonus', null=True)),
                ('dexterity_save', models.IntegerField(blank=True, help_text='Dexterity saving throw bonus', null=True)),
                ('constitution_save', models.IntegerField(blank=True, help_text='Constitution saving throw bonus', null=True)),
                ('intelligence_save', models.IntegerField(blank=True, help_text='Intelligence saving throw bonus', null=True)),
                ('wisdom_save', models.IntegerField(blank=True, help_text='Wisdom saving throw bonus', null=True)),
                ('charisma_save', models.IntegerField(blank=True, help_text='Charisma saving throw bonus', null=True)),
                ('skills', models.TextField(blank=True, help_text='Skills with bonuses', null=True)),
                ('damage_resistances', models.CharField(blank=True, help_text='Damage resistances', max_length=200, null=True)),
                ('damage_immunities', models.CharField(blank=True, help_text='Damage immunities', max_length=200, null=True)),
                ('condition_immunities', models.CharField(blank=True, help_text='Condition immunities', max_length=200, null=True)),
                ('senses', models.CharField(blank=True, help_text='Special senses', max_length=200, null=True)),
                ('multiattack', models.TextField(blank=True, help_text='Multiattack description', null=True)),
                ('actions', models.TextField(blank=True, help_text='Actions the creature can take', null=True)),
                ('bonus_actions', models.TextField(blank=True, help_text='Bonus actions', null=True)),
                ('reactions', models.TextField(blank=True, help_text='Reactions', null=True)),
                ('legendary_actions', models.TextField(blank=True, help_text='Legendary actions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='combat_tracker.combatencounter')),
            ],
            options={
                'ordering': ['-initiative_roll'],
            },
        ),
    ]
