# Generated by Django 4.2.23 on 2025-10-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_character_requirements_and_more'),
        ('monsters', '0002_alter_monster_actions_alter_monster_bonus_actions_and_more'),
        ('players', '0002_alter_player_ac_alter_player_background_and_more'),
        ('combat_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatparticipant',
            name='initiative',
            field=models.IntegerField(help_text='Initiative roll result for turn order'),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='is_dead',
            field=models.BooleanField(default=False, help_text='Whether this participant is dead or unconscious'),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='participant_type',
            field=models.CharField(choices=[('player', 'Player'), ('monster', 'Monster')], help_text='Whether this is a player character or monster', max_length=10),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='turn_completed',
            field=models.BooleanField(default=False, help_text='Whether the current turn is completed'),
        ),
        migrations.AlterField(
            model_name='combatsession',
            name='current_round',
            field=models.PositiveIntegerField(default=1, help_text='The current combat round'),
        ),
        migrations.AlterField(
            model_name='combatsession',
            name='current_turn_index',
            field=models.PositiveIntegerField(default=0, help_text='Index of current participant in initiative order'),
        ),
        migrations.AlterField(
            model_name='combatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when combat ended', null=True),
        ),
        migrations.AlterField(
            model_name='combatsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when combat began'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='campaign',
            field=models.ForeignKey(help_text='The campaign this encounter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the encounter was created'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the encounter scenario', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='monsters',
            field=models.ManyToManyField(help_text='Monsters involved in this encounter', related_name='encounters', to='monsters.monster'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='name',
            field=models.CharField(help_text='The name of the encounter', max_length=200),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='players',
            field=models.ManyToManyField(help_text='Player characters participating in this encounter', related_name='encounters', to='players.player'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the encounter was last modified'),
        ),
    ]
