# Generated by Django 4.2.23 on 2025-10-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0004_monster_gear"),
        ("players", "0004_player_subclass"),
        ("combat_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_round",
                    models.PositiveIntegerField(
                        default=1, help_text="Current combat round"
                    ),
                ),
                (
                    "current_turn_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Index of current turn in initiative order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether combat is currently active"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="When combat ended", null=True
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        help_text="The encounter this combat session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_session",
                        to="combat_tracker.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CombatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("player", "Player"), ("monster", "Monster")],
                        help_text="Whether this is a player or monster",
                        max_length=10,
                    ),
                ),
                ("initiative", models.IntegerField(help_text="Initiative roll result")),
                ("current_hp", models.IntegerField(help_text="Current hit points")),
                ("max_hp", models.IntegerField(help_text="Maximum hit points")),
                (
                    "is_dead",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this participant is dead/unconscious",
                    ),
                ),
                (
                    "turn_completed",
                    models.BooleanField(
                        default=False, help_text="Whether current turn is completed"
                    ),
                ),
                (
                    "combat_session",
                    models.ForeignKey(
                        help_text="The combat session this participant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="combat_tracker.combatsession",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monster (if participant_type is 'monster')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monsters.monster",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player character (if participant_type is 'player')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiative", "participant_type"],
            },
        ),
    ]
