# Generated by Django 4.2.23 on 2025-09-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat_tracker', '0001_initial'),
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.monster'),
        ),
    ]
