# Generated by Django 4.2.23 on 2025-09-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
        ('npcs', '0001_initial'),
        ('players', '0001_initial'),
        ('combat_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, help_text='Armor Class', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True, help_text='Current Hit Points', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='max_hit_points',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum Hit Points', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.monster'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='npcs.npc'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
