# Generated by Django 4.2.23 on 2025-09-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npcs', '0001_initial'),
        ('combat_tracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='npcs.npc'),
        ),
    ]
