# Generated by Django 4.2.23 on 2025-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_tracker', '0002_combatparticipant_armor_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='actions',
            field=models.TextField(blank=True, help_text='Actions the creature can take', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='bonus_actions',
            field=models.TextField(blank=True, help_text='Bonus actions', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='challenge_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Challenge Rating', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='charisma',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='charisma_save',
            field=models.IntegerField(blank=True, help_text='Charisma saving throw bonus', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='condition_immunities',
            field=models.CharField(blank=True, help_text='Condition immunities', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='constitution',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='constitution_save',
            field=models.IntegerField(blank=True, help_text='Constitution saving throw bonus', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='damage_immunities',
            field=models.CharField(blank=True, help_text='Damage immunities', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='damage_resistances',
            field=models.CharField(blank=True, help_text='Damage resistances', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='dexterity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='dexterity_save',
            field=models.IntegerField(blank=True, help_text='Dexterity saving throw bonus', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='intelligence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='intelligence_save',
            field=models.IntegerField(blank=True, help_text='Intelligence saving throw bonus', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='is_dead',
            field=models.BooleanField(default=False, help_text='Whether this participant is dead (0 or negative HP)'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='legendary_actions',
            field=models.TextField(blank=True, help_text='Legendary actions', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='multiattack',
            field=models.TextField(blank=True, help_text='Multiattack description', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='reactions',
            field=models.TextField(blank=True, help_text='Reactions', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='senses',
            field=models.CharField(blank=True, help_text='Special senses', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills with bonuses', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='speed',
            field=models.CharField(blank=True, help_text='Movement speed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='strength_save',
            field=models.IntegerField(blank=True, help_text='Strength saving throw bonus', null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='wisdom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='wisdom_save',
            field=models.IntegerField(blank=True, help_text='Wisdom saving throw bonus', null=True),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, help_text='Current Armor Class (can be modified by spells)', null=True),
        ),
        migrations.AlterField(
            model_name='combatparticipant',
            name='hit_points',
            field=models.IntegerField(blank=True, help_text='Current Hit Points (can go negative)', null=True),
        ),
    ]
