# Generated by Django 4.2.23 on 2025-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name or title of the campaign', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the campaign setting, story, and world', null=True)),
                ('introduction', models.TextField(blank=True, help_text='Introduction text for new players joining the campaign', null=True)),
                ('character_requirements', models.TextField(blank=True, help_text='Guidelines for character creation, restrictions, and requirements', null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
