# Generated by Django 4.2.23 on 2025-10-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Campaign title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Campaign description", null=True
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True, help_text="Campaign introduction", null=True
                    ),
                ),
                (
                    "character_requirements",
                    models.TextField(
                        blank=True, help_text="Character requirements", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
