# Generated by Django 4.2.23 on 2025-10-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = []
