# Generated by Django 4.2.23 on 2025-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='character_requirements',
            field=models.TextField(blank=True, help_text='Guidelines for character creation, restrictions, and requirements', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the campaign setting, story, and world', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='introduction',
            field=models.TextField(blank=True, help_text='Introduction text for new players joining the campaign', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='The name or title of the campaign', max_length=200),
        ),
    ]
