# Generated by Django 4.2.23 on 2025-09-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('monster_type', models.CharField(choices=[('Aberration', 'Aberration'), ('Beast', 'Beast'), ('Celestial', 'Celestial'), ('Construct', 'Construct'), ('Dragon', 'Dragon'), ('Elemental', 'Elemental'), ('Fey', 'Fey'), ('Fiend', 'Fiend'), ('Giant', 'Giant'), ('Humanoid', 'Humanoid'), ('Monstrosity', 'Monstrosity'), ('Ooze', 'Ooze'), ('Plant', 'Plant'), ('Undead', 'Undead'), ('Swarm', 'Swarm')], default='Beast', max_length=12)),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', max_length=1)),
                ('alignment', models.CharField(blank=True, help_text="e.g., 'Lawful Evil', 'Chaotic Good'", max_length=50, null=True)),
                ('challenge_rating', models.DecimalField(decimal_places=2, default=0.25, help_text='Challenge Rating (0.25, 0.5, 1, 2, etc.)', max_digits=4)),
                ('armor_class', models.PositiveIntegerField(default=10, help_text='Armor Class')),
                ('hit_points', models.PositiveIntegerField(default=8, help_text='Hit Points')),
                ('speed', models.CharField(default='30 ft.', help_text='Movement speeds', max_length=100)),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('strength_save', models.IntegerField(default=0, help_text='Strength saving throw bonus')),
                ('dexterity_save', models.IntegerField(default=0, help_text='Dexterity saving throw bonus')),
                ('constitution_save', models.IntegerField(default=0, help_text='Constitution saving throw bonus')),
                ('intelligence_save', models.IntegerField(default=0, help_text='Intelligence saving throw bonus')),
                ('wisdom_save', models.IntegerField(default=0, help_text='Wisdom saving throw bonus')),
                ('charisma_save', models.IntegerField(default=0, help_text='Charisma saving throw bonus')),
                ('skills', models.TextField(blank=True, help_text="Skills with bonuses (e.g., 'Perception +4, Stealth +6')", null=True)),
                ('damage_resistances', models.CharField(blank=True, help_text='Damage resistances', max_length=200, null=True)),
                ('damage_immunities', models.CharField(blank=True, help_text='Damage immunities', max_length=200, null=True)),
                ('condition_immunities', models.CharField(blank=True, help_text='Condition immunities', max_length=200, null=True)),
                ('senses', models.CharField(blank=True, help_text='Special senses', max_length=200, null=True)),
                ('multiattack', models.TextField(blank=True, help_text='Multiattack description', null=True)),
                ('actions', models.TextField(blank=True, help_text='Actions the monster can take', null=True)),
                ('bonus_actions', models.TextField(blank=True, help_text='Bonus actions', null=True)),
                ('reactions', models.TextField(blank=True, help_text='Reactions', null=True)),
                ('legendary_actions', models.TextField(blank=True, help_text='Legendary actions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
                'ordering': ['challenge_rating', 'name'],
            },
        ),
    ]
