# Generated by Django 4.2.23 on 2025-10-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Monster name", max_length=200)),
                ("ac", models.PositiveIntegerField(help_text="Armor Class")),
                (
                    "initiative",
                    models.CharField(
                        help_text="Initiative bonus (e.g., +16)", max_length=50
                    ),
                ),
                (
                    "hp",
                    models.CharField(
                        help_text="Hit Points (e.g., 333 (29d10 + 174))", max_length=100
                    ),
                ),
                (
                    "speed",
                    models.CharField(
                        help_text="Speed (e.g., 40 ft, Swim 10ft)", max_length=200
                    ),
                ),
                (
                    "strength",
                    models.CharField(help_text="Strength (e.g., 24 +7)", max_length=50),
                ),
                (
                    "dexterity",
                    models.CharField(
                        help_text="Dexterity (e.g., 19 +4)", max_length=50
                    ),
                ),
                (
                    "constitution",
                    models.CharField(help_text="Constitution", max_length=50),
                ),
                (
                    "intelligence",
                    models.CharField(help_text="Intelligence", max_length=50),
                ),
                ("wisdom", models.CharField(help_text="Wisdom", max_length=50)),
                ("charisma", models.CharField(help_text="Charisma", max_length=50)),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Skills and proficiencies", null=True
                    ),
                ),
                (
                    "resistances",
                    models.TextField(
                        blank=True, help_text="Damage resistances", null=True
                    ),
                ),
                (
                    "immunities",
                    models.TextField(
                        blank=True, help_text="Damage immunities", null=True
                    ),
                ),
                (
                    "senses",
                    models.TextField(
                        blank=True,
                        help_text="Senses (e.g., darkvision 60ft)",
                        null=True,
                    ),
                ),
                (
                    "languages",
                    models.TextField(
                        blank=True, help_text="Languages known", null=True
                    ),
                ),
                (
                    "challenge_rating",
                    models.CharField(
                        help_text="Challenge Rating (e.g., CR 20)", max_length=20
                    ),
                ),
                (
                    "traits",
                    models.TextField(
                        blank=True, help_text="Special traits and abilities", null=True
                    ),
                ),
                (
                    "actions",
                    models.TextField(blank=True, help_text="Actions", null=True),
                ),
                (
                    "bonus_actions",
                    models.TextField(blank=True, help_text="Bonus Actions", null=True),
                ),
                (
                    "reactions",
                    models.TextField(blank=True, help_text="Reactions", null=True),
                ),
                (
                    "legendary_actions",
                    models.TextField(
                        blank=True, help_text="Legendary Actions", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
