# Generated by Django 4.2.23 on 2025-09-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('monster_type', models.CharField(choices=[('ABERRATION', 'Aberration'), ('BEAST', 'Beast'), ('CELESTIAL', 'Celestial'), ('CONSTRUCT', 'Construct'), ('DRAGON', 'Dragon'), ('ELEMENTAL', 'Elemental'), ('FEY', 'Fey'), ('FIEND', 'Fiend'), ('GIANT', 'Giant'), ('HUMANOID', 'Humanoid'), ('MONSTROSITY', 'Monstrosity'), ('OOZE', 'Ooze'), ('PLANT', 'Plant'), ('UNDEAD', 'Undead')], default='BEAST', max_length=12)),
                ('size', models.CharField(choices=[('TINY', 'Tiny'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('HUGE', 'Huge'), ('GARGANTUAN', 'Gargantuan')], default='MEDIUM', max_length=10)),
                ('challenge_rating', models.CharField(default='1/4', help_text='Challenge Rating (e.g., 1/4, 1, 2, 5, etc.)', max_length=10)),
                ('armor_class', models.PositiveIntegerField(default=10)),
                ('hit_points', models.PositiveIntegerField(default=8)),
                ('speed', models.CharField(default='30 ft.', help_text="Movement speeds (e.g., '30 ft., fly 60 ft.')", max_length=100)),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('damage_resistances', models.TextField(blank=True, help_text='Damage resistances', null=True)),
                ('damage_immunities', models.TextField(blank=True, help_text='Damage immunities', null=True)),
                ('condition_immunities', models.TextField(blank=True, help_text='Condition immunities', null=True)),
                ('senses', models.CharField(blank=True, help_text='Special senses', max_length=200, null=True)),
                ('languages', models.CharField(blank=True, help_text='Languages spoken', max_length=200, null=True)),
                ('special_abilities', models.TextField(blank=True, help_text='Special abilities and traits', null=True)),
                ('actions', models.TextField(blank=True, help_text='Actions the monster can take', null=True)),
                ('legendary_actions', models.TextField(blank=True, help_text='Legendary actions', null=True)),
                ('description', models.TextField(blank=True, help_text='Physical description and lore', null=True)),
                ('environment', models.CharField(blank=True, help_text='Typical environment', max_length=200, null=True)),
                ('url', models.URLField(blank=True, help_text='Reference URL (e.g., D&D Beyond)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
                'ordering': ['challenge_rating', 'name'],
            },
        ),
    ]
