# Generated by Django 4.2.23 on 2025-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='actions',
            field=models.TextField(blank=True, help_text='Standard actions', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='bonus_actions',
            field=models.TextField(blank=True, help_text='Bonus actions', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.CharField(help_text="Challenge Rating (e.g., 'CR 20')", max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='charisma',
            field=models.CharField(help_text='Charisma score', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='constitution',
            field=models.CharField(help_text='Constitution score', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity',
            field=models.CharField(help_text="Dexterity score (e.g., '19 +4')", max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity_mod',
            field=models.CharField(default='+0', help_text="Dexterity Modifier (e.g., '+4')", max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity_save',
            field=models.CharField(default='+0', help_text="Dexterity Saving Throw (e.g., '+4')", max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hp',
            field=models.CharField(help_text="Hit Points with dice notation (e.g., '333 (29d10 + 174)')", max_length=100),
        ),
        migrations.AlterField(
            model_name='monster',
            name='initiative',
            field=models.CharField(help_text="Initiative bonus (e.g., '+16')", max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence',
            field=models.CharField(help_text='Intelligence score', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.TextField(blank=True, help_text='Languages the monster knows', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='legendary_actions',
            field=models.TextField(blank=True, help_text='Legendary actions (for legendary creatures)', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(help_text='The name of the monster or creature', max_length=200),
        ),
        migrations.AlterField(
            model_name='monster',
            name='senses',
            field=models.TextField(blank=True, help_text="Special senses (e.g., 'darkvision 60ft')", null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.CharField(help_text="Movement speeds (e.g., '40 ft, Swim 10ft')", max_length=200),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength',
            field=models.CharField(help_text="Strength score (e.g., '24 +7')", max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength_mod',
            field=models.CharField(default='+0', help_text="Strength Modifier (e.g., '+7')", max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength_save',
            field=models.CharField(default='+0', help_text="Strength Saving Throw (e.g., '+7')", max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wisdom',
            field=models.CharField(help_text='Wisdom score', max_length=50),
        ),
    ]
