# Generated by Django 4.2.23 on 2025-10-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="charisma_mod",
            field=models.CharField(
                default="+0", help_text="Charisma Modifier", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="charisma_save",
            field=models.CharField(
                default="+0", help_text="Charisma Saving Throw", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="constitution_mod",
            field=models.CharField(
                default="+0", help_text="Constitution Modifier", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="constitution_save",
            field=models.CharField(
                default="+0", help_text="Constitution Saving Throw", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="dexterity_mod",
            field=models.CharField(
                default="+0", help_text="Dexterity Modifier (e.g., +4)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="dexterity_save",
            field=models.CharField(
                default="+0",
                help_text="Dexterity Saving Throw (e.g., +4)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="intelligence_mod",
            field=models.CharField(
                default="+0", help_text="Intelligence Modifier", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="intelligence_save",
            field=models.CharField(
                default="+0", help_text="Intelligence Saving Throw", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="strength_mod",
            field=models.CharField(
                default="+0", help_text="Strength Modifier (e.g., +7)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="strength_save",
            field=models.CharField(
                default="+0",
                help_text="Strength Saving Throw (e.g., +7)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="wisdom_mod",
            field=models.CharField(
                default="+0", help_text="Wisdom Modifier", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="wisdom_save",
            field=models.CharField(
                default="+0", help_text="Wisdom Saving Throw", max_length=20
            ),
        ),
    ]
