# Generated by Django 4.2.23 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages known', max_length=200, null=True),
        ),
    ]
