# Generated by Django 4.2.23 on 2025-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='description',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='special_abilities',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='url',
        ),
        migrations.AddField(
            model_name='monster',
            name='alignment',
            field=models.CharField(blank=True, help_text="e.g., 'Lawful Evil', 'Chaotic Good'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='bonus_actions',
            field=models.TextField(blank=True, help_text='Bonus actions', null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='charisma_save',
            field=models.IntegerField(default=0, help_text='Charisma saving throw bonus'),
        ),
        migrations.AddField(
            model_name='monster',
            name='constitution_save',
            field=models.IntegerField(default=0, help_text='Constitution saving throw bonus'),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity_save',
            field=models.IntegerField(default=0, help_text='Dexterity saving throw bonus'),
        ),
        migrations.AddField(
            model_name='monster',
            name='intelligence_save',
            field=models.IntegerField(default=0, help_text='Intelligence saving throw bonus'),
        ),
        migrations.AddField(
            model_name='monster',
            name='multiattack',
            field=models.TextField(blank=True, help_text='Multiattack description', null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='reactions',
            field=models.TextField(blank=True, help_text='Reactions', null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.TextField(blank=True, help_text="Skills with bonuses (e.g., 'Perception +4, Stealth +6')", null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength_save',
            field=models.IntegerField(default=0, help_text='Strength saving throw bonus'),
        ),
        migrations.AddField(
            model_name='monster',
            name='wisdom_save',
            field=models.IntegerField(default=0, help_text='Wisdom saving throw bonus'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.PositiveIntegerField(default=10, help_text='Armor Class'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Challenge Rating (0.25, 0.5, 1, 2, etc.)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='monster',
            name='condition_immunities',
            field=models.CharField(blank=True, help_text='Condition immunities', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_immunities',
            field=models.CharField(blank=True, help_text='Damage immunities', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_resistances',
            field=models.CharField(blank=True, help_text='Damage resistances', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hit_points',
            field=models.PositiveIntegerField(default=8, help_text='Hit Points'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(choices=[('Aberration', 'Aberration'), ('Beast', 'Beast'), ('Celestial', 'Celestial'), ('Construct', 'Construct'), ('Dragon', 'Dragon'), ('Elemental', 'Elemental'), ('Fey', 'Fey'), ('Fiend', 'Fiend'), ('Giant', 'Giant'), ('Humanoid', 'Humanoid'), ('Monstrosity', 'Monstrosity'), ('Ooze', 'Ooze'), ('Plant', 'Plant'), ('Undead', 'Undead'), ('Swarm', 'Swarm')], default='Beast', max_length=12),
        ),
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.CharField(default='30 ft.', help_text='Movement speeds', max_length=100),
        ),
    ]
