# Generated by Django 4.2.23 on 2025-09-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('monsters', '0002_monster_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='campaigns.campaign'),
        ),
    ]
