# Generated by Django 4.2.23 on 2025-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0002_monster_charisma_mod_monster_charisma_save_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="vulnerabilities",
            field=models.TextField(
                blank=True, help_text="Damage vulnerabilities", null=True
            ),
        ),
    ]
