# Generated by Django 4.2.23 on 2025-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0003_monster_vulnerabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="gear",
            field=models.TextField(
                blank=True,
                help_text="Equipment, weapons, armor, and other gear",
                null=True,
            ),
        ),
    ]
