# Generated by Django 4.2.23 on 2025-09-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('npc_type', models.CharField(choices=[('ALLY', 'Ally'), ('NEUTRAL', 'Neutral'), ('ENEMY', 'Enemy'), ('MERCHANT', 'Merchant'), ('QUEST_GIVER', 'Quest Giver'), ('INFORMATION', 'Information Source')], default='NEUTRAL', max_length=12)),
                ('race', models.CharField(blank=True, max_length=80, null=True)),
                ('occupation', models.CharField(blank=True, max_length=80, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Where this NPC can be found', max_length=200, null=True)),
                ('url', models.URLField(blank=True, help_text='Reference URL', null=True)),
                ('armor_class', models.PositiveIntegerField(blank=True, default=10, help_text='Armor Class', null=True)),
                ('hit_points', models.PositiveIntegerField(blank=True, default=8, help_text='Hit Points', null=True)),
                ('speed', models.PositiveIntegerField(blank=True, default=30, help_text='Movement speed in feet', null=True)),
                ('disposition', models.CharField(blank=True, help_text='How they feel about the party', max_length=50, null=True)),
                ('motivation', models.TextField(blank=True, help_text='What drives this NPC', null=True)),
                ('secrets', models.TextField(blank=True, help_text='Secrets this NPC knows', null=True)),
                ('notes', models.TextField(blank=True, help_text='DM notes about this NPC', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
                'ordering': ['npc_type', 'name'],
            },
        ),
    ]
