# Generated by Django 4.2.23 on 2025-09-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('npc_type', models.CharField(choices=[('ALLY', 'Ally'), ('NEUTRAL', 'Neutral'), ('ENEMY', 'Enemy'), ('MERCHANT', 'Merchant'), ('QUESTGIVER', 'Quest Giver'), ('INFORMATION', 'Information Source')], default='NEUTRAL', max_length=12)),
                ('race', models.CharField(blank=True, help_text='Race (Human, Elf, Dwarf, etc.)', max_length=80, null=True)),
                ('occupation', models.CharField(blank=True, help_text='Occupation (Blacksmith, Merchant, Guard, etc.)', max_length=80, null=True)),
                ('disposition', models.CharField(blank=True, choices=[('Friendly', 'Friendly'), ('Neutral', 'Neutral'), ('Suspicious', 'Suspicious'), ('Hostile', 'Hostile'), ('Helpful', 'Helpful'), ('Indifferent', 'Indifferent'), ('Wary', 'Wary'), ('Enthusiastic', 'Enthusiastic'), ('Cautious', 'Cautious'), ('Welcoming', 'Welcoming'), ('Guarded', 'Guarded')], help_text='How they feel about the party', max_length=20, null=True)),
                ('motivation', models.TextField(blank=True, help_text='What drives this NPC', null=True)),
                ('secrets', models.TextField(blank=True, help_text='Secrets this NPC knows', null=True)),
                ('location', models.CharField(blank=True, help_text='Where this NPC can be found', max_length=200, null=True)),
                ('background', models.TextField(blank=True, help_text='Their history and role in the world', null=True)),
                ('armor_class', models.PositiveIntegerField(blank=True, help_text='Armor Class (only if they might fight)', null=True)),
                ('hit_points', models.PositiveIntegerField(blank=True, help_text='Hit Points (only if they might fight)', null=True)),
                ('challenge_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Challenge Rating (only if they might fight)', max_digits=3, null=True)),
                ('speed', models.CharField(blank=True, help_text="Movement speed (e.g., '30 ft.')", max_length=50, null=True)),
                ('damage_resistances', models.CharField(blank=True, help_text='Damage resistances', max_length=200, null=True)),
                ('condition_immunities', models.CharField(blank=True, help_text='Condition immunities', max_length=200, null=True)),
                ('senses', models.CharField(blank=True, help_text='Special senses', max_length=200, null=True)),
                ('actions', models.TextField(blank=True, help_text='Combat actions they can take', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
                'ordering': ['npc_type', 'name'],
            },
        ),
    ]
