# Generated by Django 4.2.23 on 2025-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='url',
        ),
        migrations.AddField(
            model_name='npc',
            name='actions',
            field=models.TextField(blank=True, help_text='Combat actions they can take', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='challenge_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Challenge Rating (only if they might fight)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='condition_immunities',
            field=models.CharField(blank=True, help_text='Condition immunities', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_resistances',
            field=models.CharField(blank=True, help_text='Damage resistances', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='senses',
            field=models.CharField(blank=True, help_text='Special senses', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, help_text='Armor Class (only if they might fight)', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='background',
            field=models.TextField(blank=True, help_text='Their history and role in the world', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Friendly', 'Friendly'), ('Neutral', 'Neutral'), ('Suspicious', 'Suspicious'), ('Hostile', 'Hostile'), ('Helpful', 'Helpful'), ('Indifferent', 'Indifferent'), ('Wary', 'Wary'), ('Enthusiastic', 'Enthusiastic'), ('Cautious', 'Cautious'), ('Welcoming', 'Welcoming'), ('Guarded', 'Guarded')], help_text='How they feel about the party', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True, help_text='Hit Points (only if they might fight)', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='npc_type',
            field=models.CharField(choices=[('ALLY', 'Ally'), ('NEUTRAL', 'Neutral'), ('ENEMY', 'Enemy'), ('MERCHANT', 'Merchant'), ('QUESTGIVER', 'Quest Giver'), ('INFORMATION', 'Information Source')], default='NEUTRAL', max_length=12),
        ),
        migrations.AlterField(
            model_name='npc',
            name='occupation',
            field=models.CharField(blank=True, help_text='Occupation (Blacksmith, Merchant, Guard, etc.)', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='race',
            field=models.CharField(blank=True, help_text='Race (Human, Elf, Dwarf, etc.)', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='speed',
            field=models.CharField(blank=True, help_text="Movement speed (e.g., '30 ft.')", max_length=50, null=True),
        ),
    ]
