# Generated by Django 4.2.23 on 2025-09-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0002_alter_npc_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='campaign',
        ),
    ]
