# Generated by Django 4.2.23 on 2025-09-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0003_remove_npc_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['challenge_rating', 'name'], 'verbose_name': 'NPC', 'verbose_name_plural': 'NPCs'},
        ),
        migrations.RemoveField(
            model_name='npc',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='npc_type',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='secrets',
        ),
        migrations.AddField(
            model_name='npc',
            name='alignment',
            field=models.CharField(blank=True, help_text="e.g., 'Lawful Evil', 'Chaotic Good'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='bonus_actions',
            field=models.TextField(blank=True, help_text='Bonus actions', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='charisma',
            field=models.PositiveIntegerField(default=10, help_text='Charisma score'),
        ),
        migrations.AddField(
            model_name='npc',
            name='charisma_save',
            field=models.IntegerField(default=0, help_text='Charisma saving throw bonus'),
        ),
        migrations.AddField(
            model_name='npc',
            name='constitution',
            field=models.PositiveIntegerField(default=10, help_text='Constitution score'),
        ),
        migrations.AddField(
            model_name='npc',
            name='constitution_save',
            field=models.IntegerField(default=0, help_text='Constitution saving throw bonus'),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage_immunities',
            field=models.CharField(blank=True, help_text='Damage immunities', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='dexterity',
            field=models.PositiveIntegerField(default=10, help_text='Dexterity score'),
        ),
        migrations.AddField(
            model_name='npc',
            name='dexterity_save',
            field=models.IntegerField(default=0, help_text='Dexterity saving throw bonus'),
        ),
        migrations.AddField(
            model_name='npc',
            name='intelligence',
            field=models.PositiveIntegerField(default=10, help_text='Intelligence score'),
        ),
        migrations.AddField(
            model_name='npc',
            name='intelligence_save',
            field=models.IntegerField(default=0, help_text='Intelligence saving throw bonus'),
        ),
        migrations.AddField(
            model_name='npc',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages known', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='legendary_actions',
            field=models.TextField(blank=True, help_text='Legendary actions', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='multiattack',
            field=models.TextField(blank=True, help_text='Multiattack description', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='reactions',
            field=models.TextField(blank=True, help_text='Reactions', null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', help_text='Creature size', max_length=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='skills',
            field=models.TextField(blank=True, help_text="Skills with bonuses (e.g., 'Perception +4, Stealth +6')", null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='strength',
            field=models.PositiveIntegerField(default=10, help_text='Strength score'),
        ),
        migrations.AddField(
            model_name='npc',
            name='strength_save',
            field=models.IntegerField(default=0, help_text='Strength saving throw bonus'),
        ),
        migrations.AddField(
            model_name='npc',
            name='wisdom',
            field=models.PositiveIntegerField(default=10, help_text='Wisdom score'),
        ),
        migrations.AddField(
            model_name='npc',
            name='wisdom_save',
            field=models.IntegerField(default=0, help_text='Wisdom saving throw bonus'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='actions',
            field=models.TextField(blank=True, help_text='Actions the NPC can take', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, help_text='Armor Class', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='challenge_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Challenge Rating (0.25, 0.5, 1, 2, etc.)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True, help_text='Hit Points', null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='speed',
            field=models.CharField(blank=True, help_text='Movement speeds', max_length=100, null=True),
        ),
    ]
