# Generated by Django 4.2.23 on 2025-09-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0004_alter_npc_options_remove_npc_disposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='alignment',
        ),
    ]
