# Generated by Django 4.2.23 on 2025-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0005_remove_npc_alignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['level', 'name'], 'verbose_name': 'NPC', 'verbose_name_plural': 'NPCs'},
        ),
        migrations.RemoveField(
            model_name='npc',
            name='challenge_rating',
        ),
        migrations.AddField(
            model_name='npc',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Character Level', null=True),
        ),
    ]
