# Generated by Django 4.2.23 on 2025-10-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(help_text='Character name', max_length=100)),
                ('player_name', models.CharField(help_text="Player's real name", max_length=100)),
                ('character_class', models.CharField(help_text='Character class (e.g., Wizard/Monk)', max_length=100)),
                ('subclass', models.CharField(blank=True, help_text='Character subclass (e.g., Beast Master, Eldritch Knight)', max_length=100, null=True)),
                ('race', models.CharField(help_text='Character race', max_length=100)),
                ('level', models.PositiveIntegerField(default=1, help_text='Character level')),
                ('ac', models.PositiveIntegerField(help_text='Armor Class')),
                ('background', models.TextField(help_text='Character background')),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['character_name'],
            },
        ),
    ]
