# Generated by Django 4.2.23 on 2025-10-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0002_auto_20251004_1510"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(help_text="Character name", max_length=100),
                ),
                (
                    "player_name",
                    models.CharField(help_text="Player's real name", max_length=100),
                ),
                (
                    "character_class",
                    models.CharField(
                        choices=[
                            ("barbarian", "Barbarian"),
                            ("bard", "Bard"),
                            ("cleric", "Cleric"),
                            ("druid", "Druid"),
                            ("fighter", "Fighter"),
                            ("monk", "Monk"),
                            ("paladin", "Paladin"),
                            ("ranger", "Ranger"),
                            ("rogue", "Rogue"),
                            ("sorcerer", "Sorcerer"),
                            ("warlock", "Warlock"),
                            ("wizard", "Wizard"),
                        ],
                        help_text="Character class",
                        max_length=20,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("dragonborn", "Dragonborn"),
                            ("dwarf", "Dwarf"),
                            ("elf", "Elf"),
                            ("gnome", "Gnome"),
                            ("half-elf", "Half-Elf"),
                            ("half-orc", "Half-Orc"),
                            ("halfling", "Halfling"),
                            ("human", "Human"),
                            ("tiefling", "Tiefling"),
                        ],
                        help_text="Character race",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=1, help_text="Character level"),
                ),
                ("ac", models.PositiveIntegerField(help_text="Armor Class")),
                (
                    "background",
                    models.CharField(help_text="Character background", max_length=100),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Associated campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["character_name"],
            },
        ),
    ]
