# Generated by Django 4.2.23 on 2025-09-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='Unknown Character', help_text="Character's name", max_length=120)),
                ('player_name', models.CharField(default='Unknown Player', help_text="Real-life player's name", max_length=120)),
                ('background', models.TextField(default='No background provided', help_text='Character background for story integration')),
                ('level', models.PositiveIntegerField(default=1, help_text='Character level')),
                ('armor_class', models.PositiveIntegerField(default=10, help_text='Armor Class for combat tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['character_name'],
            },
        ),
    ]
