# Generated by Django 4.2.23 on 2025-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="character_class",
            field=models.CharField(
                help_text="Character class (e.g., Wizard/Monk)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.CharField(help_text="Character race", max_length=100),
        ),
    ]
