# Generated by Django 4.2.23 on 2025-09-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['character_name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='player',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='player',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hit_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='player',
            name='max_hit_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passive_perception',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proficiency_bonus',
        ),
        migrations.RemoveField(
            model_name='player',
            name='race',
        ),
        migrations.RemoveField(
            model_name='player',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='player',
            name='url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='player',
            name='character_name',
            field=models.CharField(default='Unknown Character', help_text="Character's name", max_length=120),
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='Unknown Player', help_text="Real-life player's name", max_length=120),
        ),
        migrations.AlterField(
            model_name='player',
            name='armor_class',
            field=models.PositiveIntegerField(default=10, help_text='Armor Class for combat tracking'),
        ),
        migrations.AlterField(
            model_name='player',
            name='background',
            field=models.TextField(default='No background provided', help_text='Character background for story integration'),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Character level'),
        ),
    ]
