# Generated by Django 4.2.23 on 2025-10-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_character_requirements_and_more'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ac',
            field=models.PositiveIntegerField(help_text="The character's Armor Class (AC)"),
        ),
        migrations.AlterField(
            model_name='player',
            name='background',
            field=models.TextField(help_text="The character's background story, history, and personality"),
        ),
        migrations.AlterField(
            model_name='player',
            name='campaign',
            field=models.ForeignKey(help_text='The campaign this character belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='player',
            name='character_class',
            field=models.CharField(help_text="The character's class (e.g., Wizard, Fighter, Rogue, Monk)", max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='character_name',
            field=models.CharField(help_text='The name of the character in the game world', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text="The character's current level"),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(help_text='The real name of the person playing this character', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.CharField(help_text="The character's race (e.g., Human, Elf, Dragonborn, Tiefling)", max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='subclass',
            field=models.CharField(blank=True, help_text="The character's subclass (e.g., Beast Master, Eldritch Knight, Way of Shadow)", max_length=100, null=True),
        ),
    ]
