# Generated by Django 4.2.23 on 2025-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_character_class_alter_player_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="background",
            field=models.TextField(help_text="Character background"),
        ),
    ]
