# Generated by Django 4.2.23 on 2025-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="subclass",
            field=models.CharField(
                blank=True,
                help_text="Character subclass (e.g., Beast Master, Eldritch Knight)",
                max_length=100,
                null=True,
            ),
        ),
    ]
